### PR TITLE
Made The Container Fill The Screen

### PR DESCRIPTION
**Pull request by moebrowne**
Added a container that is made to fill the view port.

Also centered the city generation seed

### CODE REVIEW

**Comment by joestrong** [comment]
Cool, seems to work!

Personally I'm not too keen on how the body element is really small though. I'd prefer the body element to fill the screen, with the container being positioned relative to the body, rather than the window.

**Comment by moebrowne** [comment]
@joestrong Yeah, I started off trying to do it that way but couldn't get it to work so resorted to this solution.

Any ideas on how to go about expanding the body?

**Comment by joestrong** [comment]
The min-height 100% on html & body in your previous commits should do it. You'll also need position relative on the body too, so the container's absolute positioning will be relative to that :+1:

**Comment by moebrowne** [comment]
@joestrong I tried as you suggested, see new commits, and the `<html/>` element does now fill the view port but the `<body/>` element and all children don't 😕

**Comment by joestrong** [comment]
Thanks! I'll take a gander

**Pull request merged**
